# NOTE: update this with your service name
service: sole-life

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
   # Defines an HTTP API endpoint that calls the registerUser function in register.js
    # - path: url path is /register
    # - method: POST request
  register:
    handler: register.registerUser
    events:
      - http:
          path: register
          method: post
  health:
    handler: health.health
    events:
      - http:
          path: health
          method: get
  login:
    handler: login.loginUser
    events:
      - http:
          path: login
          method: post
  changePassword:
    handler: change-password.changePassword
    events:
      - http:
          path: changePassword
          method: post
  forgotPassword:
    handler: forgot-password.forgotPassword
    events:
      - http:
          path: forgotPasswordTriggerCode
          method: post
      - http:
          path: forgotPasswordVerifyCode
          method: post